project_id = "ygdgludwuybclprzshol"

[functions.broker-dashboard-recommendations]
verify_jwt = false

[functions.otp-verification]
verify_jwt = true

[functions.ocr-identity]
verify_jwt = true

[functions.sales-assistant]
verify_jwt = false
